name = "lean-geospatial"
version = "0.1.0"
defaultTargets = ["lean-geospatial"]

[[lean_lib]]
name = "LeanGeospatial"

[[lean_exe]]
name = "lean-geospatial"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.16.0"
