-- Generated by scripts/gen_rcc8_table.py. Do not edit by hand.

import LeanGeospatial.CompositionTable

/-!
# The 64 cells of the RCC8 weak composition table

Each theorem states one cell `r ⋄ s` exactly. They all follow from
`compose_eq_table`; the set on the right is checked against the computed
`table r s` by `decide`.
-/

namespace Geospatial.RCC8

theorem compose_dc_dc : Relation.dc ⋄ Relation.dc = ↑({.dc, .ec, .po, .eq, .tpp, .ntpp, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .dc = {.dc, .ec, .po, .eq, .tpp, .ntpp, .tppi, .ntppi} by decide]

theorem compose_dc_ec : Relation.dc ⋄ Relation.ec = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .ec = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_dc_po : Relation.dc ⋄ Relation.po = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .po = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_dc_eq : Relation.dc ⋄ Relation.eq = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .eq = {.dc} by decide]

theorem compose_dc_tpp : Relation.dc ⋄ Relation.tpp = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .tpp = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_dc_ntpp : Relation.dc ⋄ Relation.ntpp = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .ntpp = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_dc_tppi : Relation.dc ⋄ Relation.tppi = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .tppi = {.dc} by decide]

theorem compose_dc_ntppi : Relation.dc ⋄ Relation.ntppi = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .dc .ntppi = {.dc} by decide]

theorem compose_ec_dc : Relation.ec ⋄ Relation.dc = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .dc = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_ec_ec : Relation.ec ⋄ Relation.ec = ↑({.dc, .ec, .po, .eq, .tpp, .tppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .ec = {.dc, .ec, .po, .eq, .tpp, .tppi} by decide]

theorem compose_ec_po : Relation.ec ⋄ Relation.po = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .po = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_ec_eq : Relation.ec ⋄ Relation.eq = ↑({.ec} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .eq = {.ec} by decide]

theorem compose_ec_tpp : Relation.ec ⋄ Relation.tpp = ↑({.ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .tpp = {.ec, .po, .tpp, .ntpp} by decide]

theorem compose_ec_ntpp : Relation.ec ⋄ Relation.ntpp = ↑({.po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .ntpp = {.po, .tpp, .ntpp} by decide]

theorem compose_ec_tppi : Relation.ec ⋄ Relation.tppi = ↑({.dc, .ec} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .tppi = {.dc, .ec} by decide]

theorem compose_ec_ntppi : Relation.ec ⋄ Relation.ntppi = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .ec .ntppi = {.dc} by decide]

theorem compose_po_dc : Relation.po ⋄ Relation.dc = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .po .dc = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_po_ec : Relation.po ⋄ Relation.ec = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .po .ec = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_po_po : Relation.po ⋄ Relation.po = ↑({.dc, .ec, .po, .eq, .tpp, .ntpp, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .po .po = {.dc, .ec, .po, .eq, .tpp, .ntpp, .tppi, .ntppi} by decide]

theorem compose_po_eq : Relation.po ⋄ Relation.eq = ↑({.po} : Finset Relation) := by
  rw [compose_eq_table, show table .po .eq = {.po} by decide]

theorem compose_po_tpp : Relation.po ⋄ Relation.tpp = ↑({.po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .po .tpp = {.po, .tpp, .ntpp} by decide]

theorem compose_po_ntpp : Relation.po ⋄ Relation.ntpp = ↑({.po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .po .ntpp = {.po, .tpp, .ntpp} by decide]

theorem compose_po_tppi : Relation.po ⋄ Relation.tppi = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .po .tppi = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_po_ntppi : Relation.po ⋄ Relation.ntppi = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .po .ntppi = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_eq_dc : Relation.eq ⋄ Relation.dc = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .dc = {.dc} by decide]

theorem compose_eq_ec : Relation.eq ⋄ Relation.ec = ↑({.ec} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .ec = {.ec} by decide]

theorem compose_eq_po : Relation.eq ⋄ Relation.po = ↑({.po} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .po = {.po} by decide]

theorem compose_eq_eq : Relation.eq ⋄ Relation.eq = ↑({.eq} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .eq = {.eq} by decide]

theorem compose_eq_tpp : Relation.eq ⋄ Relation.tpp = ↑({.tpp} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .tpp = {.tpp} by decide]

theorem compose_eq_ntpp : Relation.eq ⋄ Relation.ntpp = ↑({.ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .ntpp = {.ntpp} by decide]

theorem compose_eq_tppi : Relation.eq ⋄ Relation.tppi = ↑({.tppi} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .tppi = {.tppi} by decide]

theorem compose_eq_ntppi : Relation.eq ⋄ Relation.ntppi = ↑({.ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .eq .ntppi = {.ntppi} by decide]

theorem compose_tpp_dc : Relation.tpp ⋄ Relation.dc = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .dc = {.dc} by decide]

theorem compose_tpp_ec : Relation.tpp ⋄ Relation.ec = ↑({.dc, .ec} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .ec = {.dc, .ec} by decide]

theorem compose_tpp_po : Relation.tpp ⋄ Relation.po = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .po = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_tpp_eq : Relation.tpp ⋄ Relation.eq = ↑({.tpp} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .eq = {.tpp} by decide]

theorem compose_tpp_tpp : Relation.tpp ⋄ Relation.tpp = ↑({.tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .tpp = {.tpp, .ntpp} by decide]

theorem compose_tpp_ntpp : Relation.tpp ⋄ Relation.ntpp = ↑({.ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .ntpp = {.ntpp} by decide]

theorem compose_tpp_tppi : Relation.tpp ⋄ Relation.tppi = ↑({.dc, .ec, .po, .eq, .tpp, .tppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .tppi = {.dc, .ec, .po, .eq, .tpp, .tppi} by decide]

theorem compose_tpp_ntppi : Relation.tpp ⋄ Relation.ntppi = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tpp .ntppi = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_ntpp_dc : Relation.ntpp ⋄ Relation.dc = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .dc = {.dc} by decide]

theorem compose_ntpp_ec : Relation.ntpp ⋄ Relation.ec = ↑({.dc} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .ec = {.dc} by decide]

theorem compose_ntpp_po : Relation.ntpp ⋄ Relation.po = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .po = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_ntpp_eq : Relation.ntpp ⋄ Relation.eq = ↑({.ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .eq = {.ntpp} by decide]

theorem compose_ntpp_tpp : Relation.ntpp ⋄ Relation.tpp = ↑({.ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .tpp = {.ntpp} by decide]

theorem compose_ntpp_ntpp : Relation.ntpp ⋄ Relation.ntpp = ↑({.ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .ntpp = {.ntpp} by decide]

theorem compose_ntpp_tppi : Relation.ntpp ⋄ Relation.tppi = ↑({.dc, .ec, .po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .tppi = {.dc, .ec, .po, .tpp, .ntpp} by decide]

theorem compose_ntpp_ntppi : Relation.ntpp ⋄ Relation.ntppi = ↑({.dc, .ec, .po, .eq, .tpp, .ntpp, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntpp .ntppi = {.dc, .ec, .po, .eq, .tpp, .ntpp, .tppi, .ntppi} by decide]

theorem compose_tppi_dc : Relation.tppi ⋄ Relation.dc = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .dc = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_tppi_ec : Relation.tppi ⋄ Relation.ec = ↑({.ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .ec = {.ec, .po, .tppi, .ntppi} by decide]

theorem compose_tppi_po : Relation.tppi ⋄ Relation.po = ↑({.po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .po = {.po, .tppi, .ntppi} by decide]

theorem compose_tppi_eq : Relation.tppi ⋄ Relation.eq = ↑({.tppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .eq = {.tppi} by decide]

theorem compose_tppi_tpp : Relation.tppi ⋄ Relation.tpp = ↑({.po, .eq, .tpp, .tppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .tpp = {.po, .eq, .tpp, .tppi} by decide]

theorem compose_tppi_ntpp : Relation.tppi ⋄ Relation.ntpp = ↑({.po, .tpp, .ntpp} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .ntpp = {.po, .tpp, .ntpp} by decide]

theorem compose_tppi_tppi : Relation.tppi ⋄ Relation.tppi = ↑({.tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .tppi = {.tppi, .ntppi} by decide]

theorem compose_tppi_ntppi : Relation.tppi ⋄ Relation.ntppi = ↑({.ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .tppi .ntppi = {.ntppi} by decide]

theorem compose_ntppi_dc : Relation.ntppi ⋄ Relation.dc = ↑({.dc, .ec, .po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .dc = {.dc, .ec, .po, .tppi, .ntppi} by decide]

theorem compose_ntppi_ec : Relation.ntppi ⋄ Relation.ec = ↑({.po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .ec = {.po, .tppi, .ntppi} by decide]

theorem compose_ntppi_po : Relation.ntppi ⋄ Relation.po = ↑({.po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .po = {.po, .tppi, .ntppi} by decide]

theorem compose_ntppi_eq : Relation.ntppi ⋄ Relation.eq = ↑({.ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .eq = {.ntppi} by decide]

theorem compose_ntppi_tpp : Relation.ntppi ⋄ Relation.tpp = ↑({.po, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .tpp = {.po, .tppi, .ntppi} by decide]

theorem compose_ntppi_ntpp : Relation.ntppi ⋄ Relation.ntpp = ↑({.po, .eq, .tpp, .ntpp, .tppi, .ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .ntpp = {.po, .eq, .tpp, .ntpp, .tppi, .ntppi} by decide]

theorem compose_ntppi_tppi : Relation.ntppi ⋄ Relation.tppi = ↑({.ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .tppi = {.ntppi} by decide]

theorem compose_ntppi_ntppi : Relation.ntppi ⋄ Relation.ntppi = ↑({.ntppi} : Finset Relation) := by
  rw [compose_eq_table, show table .ntppi .ntppi = {.ntppi} by decide]

end Geospatial.RCC8
