#!/usr/bin/env python3
"""Generate the witnesses that the RCC8 table is complete on the real line.

Outputs (all generated, do not edit by hand):

  data/line_witnesses.tsv                 one witness per line
  LeanGeospatial/Line/Witnesses.lean      the witnesses as a Lean function

An area of the line is represented by a finite set S of integers, standing
for the union of the unit cells [i, i + 1], i in S. The relation between two
such areas is computed exactly as `cellRel` in LeanGeospatial/Line/Cells.lean
computes it. The table comes from rcc8_model.py, which mirrors the Lean
definition. For every entry t of table(r, s) the script finds sets S, T, U with
cellRel S T = r, cellRel T U = s, cellRel S U = t, preferring fewer cells.
Lean checks every witness by `decide`; this script is not trusted.

Usage: python3 scripts/gen_line_witnesses.py
"""
import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from rcc8_model import RELS, table  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = "-- Generated by scripts/gen_line_witnesses.py. Do not edit by hand.\n"
CELLS = 5


def cell_rel(S, T):
    if not any(j in (i - 1, i, i + 1) for i in S for j in T):
        return "dc"
    if not (S & T):
        return "ec"
    if S == T:
        return "eq"
    if S <= T:
        return "ntpp" if all({i - 1, i, i + 1} <= T for i in S) else "tpp"
    if T <= S:
        return "ntppi" if all({i - 1, i, i + 1} <= S for i in T) else "tppi"
    return "po"


def sets():
    """Nonempty subsets of range(CELLS), fewest cells and smallest first."""
    out = []
    for k in range(1, CELLS + 1):
        for c in itertools.combinations(range(CELLS), k):
            out.append(frozenset(c))
    return out


def find():
    ss = sets()
    rel = {(a, b): cell_rel(a, b) for a in ss for b in ss}
    found = {}
    for a, b, c in sorted(itertools.product(ss, ss, ss),
                          key=lambda w: (sum(map(len, w)), [sorted(x) for x in w])):
        key = (rel[(a, b)], rel[(b, c)], rel[(a, c)])
        found.setdefault(key, (a, b, c))
    need = [(r, s, t) for r in RELS for s in RELS for t in RELS if t in table(r, s)]
    missing = [k for k in need if k not in found]
    if missing:
        sys.exit(f"no witness for {missing}")
    extra = [k for k in found if k[2] not in table(k[0], k[1])]
    if extra:
        sys.exit(f"table not sound for cells: {extra}")
    return {k: found[k] for k in need}


def lean_set(x):
    return "{" + ", ".join(str(i) for i in sorted(x)) + "}"


def write(path, text):
    with open(os.path.join(ROOT, path), "w") as f:
        f.write(text)


def main():
    w = find()
    rows = ["r\ts\tt\tS\tT\tU"]
    for (r, s, t), (a, b, c) in w.items():
        rows.append("\t".join([r, s, t] + [",".join(map(str, sorted(x))) for x in (a, b, c)]))
    write("data/line_witnesses.tsv", "\n".join(rows) + "\n")
    out = [HEADER, "import LeanGeospatial.Line.Cells\n",
           "/-!\n# Witnesses on the line\n\n"
           "For every entry `t` of `table r s`, three sets of cells `S, T, U` with\n"
           "`cellRel S T = r`, `cellRel T U = s` and `cellRel S U = t`, found by\n"
           "`scripts/gen_line_witnesses.py` among the unions of at most five cells.\n"
           "`LeanGeospatial/Line.lean` checks them all by `decide`.\n-/\n",
           "namespace Geospatial.Line\n",
           "open Geospatial.RCC8\n",
           "/-- A witness for each entry of the table; `(∅, ∅, ∅)` off the table. -/",
           "def lineWitness : Relation → Relation → Relation → Finset ℤ × Finset ℤ × Finset ℤ"]
    for (r, s, t), (a, b, c) in w.items():
        out.append(f"  | .{r}, .{s}, .{t} => ({lean_set(a)}, {lean_set(b)}, {lean_set(c)})")
    out.append("  | _, _, _ => (∅, ∅, ∅)\n")
    out.append("end Geospatial.Line\n")
    write("LeanGeospatial/Line/Witnesses.lean", "\n".join(out))
    print(f"witnesses: {len(w)}, most cells in one set: "
          f"{max(len(x) for v in w.values() for x in v)}")


if __name__ == "__main__":
    main()
