#!/usr/bin/env python3
"""Generate the RCC8 composition table files.

Outputs (all generated, do not edit by hand):

  data/rcc8_witnesses.tsv                      one witness per line
  LeanGeospatial/RCC8Witnesses/Triples.lean    one theorem per witness
  LeanGeospatial/CompositionTable/Complete.lean  every (r, s, t) resolved
  LeanGeospatial/CompositionTable/Cells.lean   the 64 cells as theorems
  LeanGeospatial/Examples/PublishedTable.lean  comparison with the literature

The table itself comes from the Lean definitions (`table` in
CompositionTable/Abstract.lean), mirrored in rcc8_model.py. This script only
searches for rectangles that witness each entry and writes the proof
skeletons; Lean checks every one of them. The published table in
data/rcc8_known_table.tsv is read only to write the comparison file.

Usage: python3 scripts/gen_rcc8_table.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from rcc8_model import CONVERSE, RELS, canonical, rects, rel, table  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = "-- Generated by scripts/gen_rcc8_table.py. Do not edit by hand.\n"


def lean_rect(r):
    x0, x1, y0, y1 = r
    return f"⟨{x0}, {x1}, {y0}, {y1}⟩"


def witness_name(r, s, t):
    return f"realizes_{r}_{s}_{t}"


def find_witnesses():
    """A rectangle triple for every t in table(r, s), canonical non-EQ cells."""
    # Small rectangles first, so the witnesses stay readable.
    pool = sorted(rects(0, 6), key=lambda q: (max(q), q[1] - q[0] + q[3] - q[2], q))
    by_rel = {}
    for a in pool:
        for b in pool:
            by_rel.setdefault(rel(a, b), []).append((a, b))
    found = {}
    for r in RELS:
        for s in RELS:
            if "eq" in (r, s) or canonical(r, s) != (r, s):
                continue
            for t in table(r, s):
                hit = None
                for a, b in by_rel[r]:
                    for c in pool:
                        if rel(b, c) == s and rel(a, c) == t:
                            hit = (a, b, c)
                            break
                    if hit:
                        break
                if hit is None:
                    sys.exit(f"no rectangle witness for {t} in {r} ⋄ {s}")
                found[(r, s, t)] = hit
    return found


def write(path, text):
    with open(os.path.join(ROOT, path), "w") as f:
        f.write(text)


def gen_tsv(found):
    lines = ["r\ts\tt\tA\tB\tC"]
    for (r, s, t), (a, b, c) in sorted(found.items(), key=lambda kv: tuple(RELS.index(x) for x in kv[0])):
        fmt = lambda q: ",".join(map(str, q))
        lines.append(f"{r}\t{s}\t{t}\t{fmt(a)}\t{fmt(b)}\t{fmt(c)}")
    write("data/rcc8_witnesses.tsv", "\n".join(lines) + "\n")


def gen_triples(found):
    out = [HEADER, "import LeanGeospatial.RCC8Witnesses\n",
           "/-!\n# Rectangle witnesses for the composition table\n",
           "One theorem per entry `t ∈ r ⋄ s` of a representative cell: rectangles",
           "`A`, `B`, `C` (as `⟨xmin, xmax, ymin, ymax⟩`) with `r A B`, `s B C`, `t A C`.",
           "Cells involving `EQ`, and cells that are the converse of a representative,",
           "reuse these through `realizes_eq_left`, `realizes_eq_right` and",
           "`Realizes.converse`. Each relation is checked by `rect_rcc8`.\n-/\n",
           "namespace Geospatial.RCC8.Witnesses\n", "open Geospatial Geospatial.RCC8\n"]
    for (r, s, t), (a, b, c) in sorted(found.items(), key=lambda kv: tuple(RELS.index(x) for x in kv[0])):
        out.append(f"theorem {witness_name(r, s, t)} : Realizes .{r} .{s} .{t} :=\n"
                   f"  realizes_of_rects {lean_rect(a)} {lean_rect(b)} {lean_rect(c)}\n"
                   f"    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)\n")
    out.append("end Geospatial.RCC8.Witnesses\n")
    write("LeanGeospatial/RCC8Witnesses/Triples.lean", "\n".join(out))


def gen_complete(found):
    out = [HEADER, "import LeanGeospatial.CompositionTable.Abstract",
           "import LeanGeospatial.RCC8Witnesses.Triples\n",
           "/-!\n# Every entry of the computed table is realised\n",
           "One line per `(r, s, t)`: an entry of `table r s` is realised by a",
           "rectangle witness, by the converse of one, or by `EQ` being an identity;",
           "anything else is not in the table, which `decide` confirms.\n-/\n",
           "namespace Geospatial.RCC8\n", "open Geospatial Witnesses\n",
           "theorem realizes_of_mem_table : ∀ r s t : Relation, t ∈ table r s → Realizes r s t"]
    for r in RELS:
        for s in RELS:
            cell = table(r, s)
            for t in RELS:
                pat = f"  | .{r}, .{s}, .{t}, "
                if t not in cell:
                    out.append(pat + "h => absurd h (by decide)")
                elif r == "eq":
                    out.append(pat + "_ => realizes_eq_left _")
                elif s == "eq":
                    out.append(pat + "_ => realizes_eq_right _")
                elif canonical(r, s) == (r, s):
                    out.append(pat + f"_ => {witness_name(r, s, t)}")
                else:
                    rr, ss, tt = CONVERSE[s], CONVERSE[r], CONVERSE[t]
                    assert (rr, ss, tt) in found, (r, s, t)
                    out.append(pat + f"_ => {witness_name(rr, ss, tt)}.converse")
    out.append("\nend Geospatial.RCC8\n")
    write("LeanGeospatial/CompositionTable/Complete.lean", "\n".join(out))


def finset(ts):
    return "{" + ", ".join(f".{t}" for t in ts) + "}"


def gen_cells():
    out = [HEADER, "import LeanGeospatial.CompositionTable\n",
           "/-!\n# The 64 cells of the RCC8 weak composition table\n",
           "Each theorem states one cell `r ⋄ s` exactly. They all follow from",
           "`compose_eq_table`; the set on the right is checked against the computed",
           "`table r s` by `decide`.\n-/\n",
           "namespace Geospatial.RCC8\n"]
    for r in RELS:
        for s in RELS:
            ts = table(r, s)
            out.append(f"theorem compose_{r}_{s} : Relation.{r} ⋄ Relation.{s} = "
                       f"↑({finset(ts)} : Finset Relation) := by\n"
                       f"  rw [compose_eq_table, show table .{r} .{s} = {finset(ts)} by decide]\n")
    out.append("end Geospatial.RCC8\n")
    write("LeanGeospatial/CompositionTable/Cells.lean", "\n".join(out))


def read_known():
    known = {}
    src = ""
    with open(os.path.join(ROOT, "data/rcc8_known_table.tsv")) as f:
        for line in f:
            if line.startswith("# Source:"):
                src = line[len("# Source:"):].strip()
            if line.startswith("#") or line.startswith("r\t"):
                continue
            r, s, res = line.rstrip("\n").split("\t")
            known[(r, s)] = res.split(",")
    return known, src


def gen_published():
    known, src = read_known()
    out = [HEADER, "import LeanGeospatial.CompositionTable.Abstract\n",
           "/-!\n# Comparison with the published RCC8 composition table\n",
           f"`published` transcribes the table from {src}",
           "(data/rcc8_known_table.tsv). It is not used by any proof in the library;",
           "this file only checks that the table derived from LeanGeospatial's own",
           "definitions agrees with it cell by cell.\n-/\n",
           "namespace Geospatial.Examples.PublishedTable\n",
           "open Geospatial.RCC8\n",
           "/-- The published table, for comparison only. -/",
           "def published : Relation → Relation → Finset Relation"]
    for r in RELS:
        for s in RELS:
            out.append(f"  | .{r}, .{s} => {finset(known[(r, s)])}")
    out.append("\n/-- The derived table and the published one agree on all 64 cells. -/")
    out.append("theorem table_eq_published (r s : Relation) : table r s = published r s := by")
    out.append("  cases r <;> cases s <;> decide\n")
    out.append("end Geospatial.Examples.PublishedTable\n")
    write("LeanGeospatial/Examples/PublishedTable.lean", "\n".join(out))
    diffs = [(r, s) for r in RELS for s in RELS if sorted(table(r, s)) != sorted(known[(r, s)])]
    return diffs


def main():
    found = find_witnesses()
    gen_tsv(found)
    gen_triples(found)
    gen_complete(found)
    gen_cells()
    diffs = gen_published()
    print(f"witnesses: {len(found)}")
    print(f"cells differing from the published table: {len(diffs)}")
    for r, s in diffs:
        print(f"  {r} ⋄ {s}: derived {table(r, s)}")


if __name__ == "__main__":
    main()
