#!/usr/bin/env python3
"""Generate the witnesses that the RCC8 table is complete on the circle with
connected areas.

Outputs (all generated, do not edit by hand):

  data/circle_witnesses.tsv               one witness per line
  LeanGeospatial/Circle/Witnesses.lean    the witnesses as a Lean function

The circle is the line wrapped with period 6, cut into six unit cells. An arc
is a run of consecutive cells [a, b) of the line, 0 <= a < 6, a < b <= a + 6,
wrapped onto the circle; it is connected. The relation between two arcs is
computed exactly as `cycRel` in LeanGeospatial/Circle/Cells.lean computes it,
on the residues mod 6 of their cells. For every entry t of table(r, s) the
script finds three arcs with the right relations, preferring shorter ones.
Lean checks every witness by `decide`; this script is not trusted.

Usage: python3 scripts/gen_circle_witnesses.py
"""
import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from rcc8_model import RELS, table  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = "-- Generated by scripts/gen_circle_witnesses.py. Do not edit by hand.\n"
N = 6


def residues(arc):
    a, b = arc
    return frozenset(i % N for i in range(a, b))


def cyc_rel(A, B):
    nb = lambda i: {(i - 1) % N, i, (i + 1) % N}
    if not any(j in nb(i) for i in A for j in B):
        return "dc"
    if not (A & B):
        return "ec"
    if A == B:
        return "eq"
    if A <= B:
        return "ntpp" if all(nb(i) <= B for i in A) else "tpp"
    if B <= A:
        return "ntppi" if all(nb(i) <= A for i in B) else "tppi"
    return "po"


def arcs():
    return sorted(((a, a + l) for a in range(N) for l in range(1, N + 1)),
                  key=lambda w: (w[1] - w[0], w[0]))


def find():
    xs = arcs()
    res = {w: residues(w) for w in xs}
    rel = {(u, v): cyc_rel(res[u], res[v]) for u in xs for v in xs}
    found = {}
    for u, v, w in sorted(itertools.product(xs, xs, xs),
                          key=lambda t: (sum(b - a for a, b in t), t)):
        found.setdefault((rel[(u, v)], rel[(v, w)], rel[(u, w)]), (u, v, w))
    need = [(r, s, t) for r in RELS for s in RELS for t in RELS if t in table(r, s)]
    missing = [k for k in need if k not in found]
    if missing:
        sys.exit(f"no witness for {missing}")
    extra = [k for k in found if k[2] not in table(k[0], k[1])]
    if extra:
        sys.exit(f"table not sound for arcs: {extra}")
    return {k: found[k] for k in need}


def write(path, text):
    with open(os.path.join(ROOT, path), "w") as f:
        f.write(text)


def main():
    w = find()
    rows = ["r\ts\tt\tA\tB\tC"]
    for (r, s, t), arcs3 in w.items():
        rows.append("\t".join([r, s, t] + [f"{a},{b}" for a, b in arcs3]))
    write("data/circle_witnesses.tsv", "\n".join(rows) + "\n")
    out = [HEADER, "import LeanGeospatial.Circle.Cells\n",
           "/-!\n# Witnesses on the circle\n\n"
           "For every entry `t` of `table r s`, three arcs `[a, b)` of cells, wrapped\n"
           "onto the circle of period `6`, with the relations `r`, `s`, `t`, found by\n"
           "`scripts/gen_circle_witnesses.py`. `LeanGeospatial/Circle.lean` checks them\n"
           "all by `decide`.\n-/\n",
           "namespace Geospatial.Cyc\n",
           "open Geospatial.RCC8\n",
           "/-- Three arcs for each entry of the table; `((0, 0), (0, 0), (0, 0))` off\nthe table. -/",
           "def circleWitness : Relation → Relation → Relation → (ℤ × ℤ) × (ℤ × ℤ) × (ℤ × ℤ)"]
    for (r, s, t), ((a1, b1), (a2, b2), (a3, b3)) in w.items():
        out.append(f"  | .{r}, .{s}, .{t} => (({a1}, {b1}), ({a2}, {b2}), ({a3}, {b3}))")
    out.append("  | _, _, _ => ((0, 0), (0, 0), (0, 0))\n")
    out.append("end Geospatial.Cyc\n")
    write("LeanGeospatial/Circle/Witnesses.lean", "\n".join(out))
    print(f"witnesses: {len(w)}, longest arc: {max(b - a for v in w.values() for a, b in v)} cells")


if __name__ == "__main__":
    main()
