-- Generated by scripts/gen_rcc8_table.py. Do not edit by hand.

import LeanGeospatial.RCC8Witnesses

/-!
# Rectangle witnesses for the composition table

One theorem per entry `t ∈ r ⋄ s` of a representative cell: rectangles
`A`, `B`, `C` (as `⟨xmin, xmax, ymin, ymax⟩`) with `r A B`, `s B C`, `t A C`.
Cells involving `EQ`, and cells that are the converse of a representative,
reuse these through `realizes_eq_left`, `realizes_eq_right` and
`Realizes.converse`. Each relation is checked by `rect_rcc8`.
-/

namespace Geospatial.RCC8.Witnesses

open Geospatial Geospatial.RCC8

theorem realizes_dc_dc_dc : Realizes .dc .dc .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨2, 3, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_ec : Realizes .dc .dc .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨1, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_po : Realizes .dc .dc .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨2, 3, 0, 1⟩ ⟨0, 1, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_eq : Realizes .dc .dc .eq :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_tpp : Realizes .dc .dc .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_ntpp : Realizes .dc .dc .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 1, 4, 5⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_tppi : Realizes .dc .dc .tppi :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨2, 3, 0, 1⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_dc_ntppi : Realizes .dc .dc .ntppi :=
  realizes_of_rects ⟨0, 3, 0, 3⟩ ⟨0, 1, 4, 5⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ec_dc : Realizes .dc .ec .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨1, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ec_ec : Realizes .dc .ec .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 1, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ec_po : Realizes .dc .ec .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨2, 3, 0, 1⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ec_tpp : Realizes .dc .ec .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ec_ntpp : Realizes .dc .ec .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 1, 3, 4⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_po_dc : Realizes .dc .po .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 2, 3⟩ ⟨1, 3, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_po_ec : Realizes .dc .po .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 2, 3⟩ ⟨0, 1, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_po_po : Realizes .dc .po .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨2, 3, 0, 2⟩ ⟨0, 3, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_po_tpp : Realizes .dc .po .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 2, 3⟩ ⟨0, 1, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_po_ntpp : Realizes .dc .po .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨2, 4, 3, 4⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_tpp_dc : Realizes .dc .tpp .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_tpp_ec : Realizes .dc .tpp .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 1, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_tpp_po : Realizes .dc .tpp .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨2, 3, 0, 1⟩ ⟨0, 3, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_tpp_tpp : Realizes .dc .tpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 2, 3⟩ ⟨0, 1, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_tpp_ntpp : Realizes .dc .tpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 1, 3, 4⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ntpp_dc : Realizes .dc .ntpp .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨1, 2, 3, 4⟩ ⟨0, 3, 2, 5⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ntpp_ec : Realizes .dc .ntpp .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨1, 2, 2, 3⟩ ⟨0, 3, 1, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ntpp_po : Realizes .dc .ntpp .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨2, 3, 2, 3⟩ ⟨0, 4, 1, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ntpp_tpp : Realizes .dc .ntpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨1, 2, 2, 3⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ntpp_ntpp : Realizes .dc .ntpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨1, 2, 3, 4⟩ ⟨0, 3, 0, 5⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_tppi_dc : Realizes .dc .tppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 2, 3⟩ ⟨0, 1, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_dc_ntppi_dc : Realizes .dc .ntppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 3, 2, 5⟩ ⟨1, 2, 3, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ec_dc : Realizes .ec .ec .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 2⟩ ⟨0, 1, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ec_ec : Realizes .ec .ec .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 2⟩ ⟨1, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ec_po : Realizes .ec .ec .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨1, 2, 0, 1⟩ ⟨0, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ec_eq : Realizes .ec .ec .eq :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 2⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ec_tpp : Realizes .ec .ec .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 2⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ec_tppi : Realizes .ec .ec .tppi :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨1, 2, 0, 1⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_po_dc : Realizes .ec .po .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 3⟩ ⟨0, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_po_ec : Realizes .ec .po .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 1, 2⟩ ⟨1, 2, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_po_po : Realizes .ec .po .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨1, 2, 0, 2⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_po_tpp : Realizes .ec .po .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 1, 2⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_po_ntpp : Realizes .ec .po .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 1, 2, 4⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_tpp_ec : Realizes .ec .tpp .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 2⟩ ⟨0, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_tpp_po : Realizes .ec .tpp .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨1, 2, 0, 1⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_tpp_tpp : Realizes .ec .tpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 2⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_tpp_ntpp : Realizes .ec .tpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 1, 0, 1⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ntpp_po : Realizes .ec .ntpp .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨1, 2, 2, 3⟩ ⟨0, 3, 1, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ntpp_tpp : Realizes .ec .ntpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ntpp_ntpp : Realizes .ec .ntpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨1, 2, 2, 3⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_tppi_dc : Realizes .ec .tppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 1, 3⟩ ⟨0, 1, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_tppi_ec : Realizes .ec .tppi .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 1, 2⟩ ⟨0, 1, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ec_ntppi_dc : Realizes .ec .ntppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 3, 1, 4⟩ ⟨1, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_dc : Realizes .po .po .dc :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 3, 0, 1⟩ ⟨2, 3, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_ec : Realizes .po .po .ec :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨1, 2, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_po : Realizes .po .po .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 1, 2⟩ ⟨0, 1, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_eq : Realizes .po .po .eq :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_tpp : Realizes .po .po .tpp :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨0, 1, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_ntpp : Realizes .po .po .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 3⟩ ⟨1, 4, 1, 2⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_tppi : Realizes .po .po .tppi :=
  realizes_of_rects ⟨0, 2, 0, 2⟩ ⟨0, 1, 1, 3⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_po_ntppi : Realizes .po .po .ntppi :=
  realizes_of_rects ⟨0, 3, 0, 4⟩ ⟨1, 4, 1, 2⟩ ⟨1, 2, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tpp_po : Realizes .po .tpp .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨0, 3, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tpp_tpp : Realizes .po .tpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨0, 2, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tpp_ntpp : Realizes .po .tpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 3⟩ ⟨0, 2, 1, 2⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntpp_po : Realizes .po .ntpp .po :=
  realizes_of_rects ⟨0, 3, 1, 2⟩ ⟨2, 3, 1, 3⟩ ⟨1, 4, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntpp_tpp : Realizes .po .ntpp .tpp :=
  realizes_of_rects ⟨0, 2, 1, 2⟩ ⟨1, 2, 1, 3⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntpp_ntpp : Realizes .po .ntpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 3⟩ ⟨1, 3, 1, 2⟩ ⟨0, 4, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tppi_dc : Realizes .po .tppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 3, 0, 1⟩ ⟨2, 3, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tppi_ec : Realizes .po .tppi .ec :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨1, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tppi_po : Realizes .po .tppi .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 1, 3⟩ ⟨0, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tppi_tppi : Realizes .po .tppi .tppi :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 1⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_tppi_ntppi : Realizes .po .tppi .ntppi :=
  realizes_of_rects ⟨0, 3, 0, 3⟩ ⟨1, 2, 1, 4⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntppi_dc : Realizes .po .ntppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 4, 1, 4⟩ ⟨2, 3, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntppi_ec : Realizes .po .ntppi .ec :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 3, 1, 4⟩ ⟨1, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntppi_po : Realizes .po .ntppi .po :=
  realizes_of_rects ⟨0, 3, 1, 2⟩ ⟨1, 4, 0, 4⟩ ⟨2, 3, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntppi_tppi : Realizes .po .ntppi .tppi :=
  realizes_of_rects ⟨0, 3, 1, 2⟩ ⟨1, 4, 0, 3⟩ ⟨2, 3, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_po_ntppi_ntppi : Realizes .po .ntppi .ntppi :=
  realizes_of_rects ⟨0, 3, 0, 4⟩ ⟨0, 4, 0, 3⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tpp_tpp : Realizes .tpp .tpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tpp_ntpp : Realizes .tpp .tpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_ntpp_ntpp : Realizes .tpp .ntpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨1, 2, 1, 3⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tppi_dc : Realizes .tpp .tppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 0, 3⟩ ⟨0, 1, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tppi_ec : Realizes .tpp .tppi .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 0, 2⟩ ⟨0, 1, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tppi_po : Realizes .tpp .tppi .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 2⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tppi_eq : Realizes .tpp .tppi .eq :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 1, 0, 2⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tppi_tpp : Realizes .tpp .tppi .tpp :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 2, 0, 2⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_tppi_tppi : Realizes .tpp .tppi .tppi :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 2, 0, 2⟩ ⟨0, 1, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_ntppi_dc : Realizes .tpp .ntppi .dc :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 3, 0, 4⟩ ⟨1, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_ntppi_ec : Realizes .tpp .ntppi .ec :=
  realizes_of_rects ⟨0, 1, 0, 1⟩ ⟨0, 3, 0, 3⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_ntppi_po : Realizes .tpp .ntppi .po :=
  realizes_of_rects ⟨0, 2, 1, 2⟩ ⟨0, 3, 0, 4⟩ ⟨1, 2, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_ntppi_tppi : Realizes .tpp .ntppi .tppi :=
  realizes_of_rects ⟨0, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tpp_ntppi_ntppi : Realizes .tpp .ntppi .ntppi :=
  realizes_of_rects ⟨0, 3, 0, 3⟩ ⟨0, 3, 0, 4⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_tpp_ntpp : Realizes .ntpp .tpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntpp_ntpp : Realizes .ntpp .ntpp .ntpp :=
  realizes_of_rects ⟨2, 3, 2, 3⟩ ⟨1, 4, 1, 4⟩ ⟨0, 5, 0, 5⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_dc : Realizes .ntpp .ntppi .dc :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 5⟩ ⟨1, 2, 3, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_ec : Realizes .ntpp .ntppi .ec :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 4⟩ ⟨1, 2, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_po : Realizes .ntpp .ntppi .po :=
  realizes_of_rects ⟨1, 2, 1, 3⟩ ⟨0, 4, 0, 4⟩ ⟨1, 3, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_eq : Realizes .ntpp .ntppi .eq :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_tpp : Realizes .ntpp .ntppi .tpp :=
  realizes_of_rects ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 4⟩ ⟨1, 2, 1, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_ntpp : Realizes .ntpp .ntppi .ntpp :=
  realizes_of_rects ⟨2, 3, 2, 3⟩ ⟨0, 5, 0, 5⟩ ⟨1, 4, 1, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_tppi : Realizes .ntpp .ntppi .tppi :=
  realizes_of_rects ⟨1, 2, 1, 3⟩ ⟨0, 3, 0, 4⟩ ⟨1, 2, 1, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntpp_ntppi_ntppi : Realizes .ntpp .ntppi .ntppi :=
  realizes_of_rects ⟨1, 4, 1, 4⟩ ⟨0, 5, 0, 5⟩ ⟨2, 3, 2, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_tpp_po : Realizes .tppi .tpp .po :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 1, 0, 1⟩ ⟨0, 2, 0, 1⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_tpp_eq : Realizes .tppi .tpp .eq :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 1, 0, 1⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_tpp_tpp : Realizes .tppi .tpp .tpp :=
  realizes_of_rects ⟨0, 1, 0, 2⟩ ⟨0, 1, 0, 1⟩ ⟨0, 2, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_tpp_tppi : Realizes .tppi .tpp .tppi :=
  realizes_of_rects ⟨0, 2, 0, 2⟩ ⟨0, 1, 0, 1⟩ ⟨0, 1, 0, 2⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_ntpp_po : Realizes .tppi .ntpp .po :=
  realizes_of_rects ⟨0, 3, 1, 2⟩ ⟨2, 3, 1, 2⟩ ⟨1, 4, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_ntpp_tpp : Realizes .tppi .ntpp .tpp :=
  realizes_of_rects ⟨0, 2, 1, 2⟩ ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_tppi_ntpp_ntpp : Realizes .tppi .ntpp .ntpp :=
  realizes_of_rects ⟨1, 2, 1, 3⟩ ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntppi_ntpp_po : Realizes .ntppi .ntpp .po :=
  realizes_of_rects ⟨0, 3, 0, 4⟩ ⟨1, 2, 1, 2⟩ ⟨0, 4, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntppi_ntpp_eq : Realizes .ntppi .ntpp .eq :=
  realizes_of_rects ⟨0, 3, 0, 3⟩ ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntppi_ntpp_tpp : Realizes .ntppi .ntpp .tpp :=
  realizes_of_rects ⟨0, 3, 0, 3⟩ ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntppi_ntpp_ntpp : Realizes .ntppi .ntpp .ntpp :=
  realizes_of_rects ⟨1, 4, 1, 4⟩ ⟨2, 3, 2, 3⟩ ⟨0, 5, 0, 5⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntppi_ntpp_tppi : Realizes .ntppi .ntpp .tppi :=
  realizes_of_rects ⟨0, 3, 0, 4⟩ ⟨1, 2, 1, 2⟩ ⟨0, 3, 0, 3⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

theorem realizes_ntppi_ntpp_ntppi : Realizes .ntppi .ntpp .ntppi :=
  realizes_of_rects ⟨0, 5, 0, 5⟩ ⟨2, 3, 2, 3⟩ ⟨1, 4, 1, 4⟩
    (by norm_num) (by norm_num) (by norm_num) (by rect_rcc8) (by rect_rcc8) (by rect_rcc8)

end Geospatial.RCC8.Witnesses
